const {
  PRODUCTION: RAW_PRODUCTION_FLAG,
  CMS_SPACE_ID = "",
  CMS_DELIVERY_APIKEY = "",
  CMS_PREVIEW_APIKEY = "",
} = process.env;

const PRODUCTION = Number(RAW_PRODUCTION_FLAG);

export { PRODUCTION, CMS_SPACE_ID, CMS_DELIVERY_APIKEY, CMS_PREVIEW_APIKEY };
